### ISSUE TITLE
`#[derive(Optic)]` is shown in README but not actually available

### ISSUE THREAD

**Issue by maackle** [TOETOE55/lens-rs#1]
`derive_optic` was removed but the README still references it.

https://github.com/TOETOE55/lens-rs/commit/3c19d0d2516dd0ca128972bcd194da861cf0ae5d#diff-dc4a22e0b81ffbabfdb6f61ae197ca2f0a406ddf9141d14e930b56b5df7b3a74R41

How can we have optics on struct fields now?

I know this crate is very new, but I'm excited about it. Nice work!

**Comment by TOETOE55** [comment]
hello!

You have no need to `#[derive(Optic)]` now!
After version 0.1, `lens-rs` will scan your source code, 
and generate optics into `lens_rs::optics` for fields and variants where you marked as `#[optic]` .

I'm glad someone is using this library! thank u =)

**Comment by maackle** [comment]
I thought so! But, I am still having an error with a very basic example. Can you help?

```rust
#[test]
fn example_lens_rs() {
    use lens_rs::*;

    #[derive(Lens, Debug)]
    struct S {
        #[optic]
        x: i32,
    }

    let s = S { x: 11 };
    optics!(x).view(s);
}
```

This leads to errors:

```
error[E0412]: cannot find type `x` in module `lens_rs::optics`
 --> src/lib.rs:8:9
  |
8 |         x: i32,
  |         ^ not found in `lens_rs::optics`

error[E0425]: cannot find function `x` in module `lens_rs::optics`
  --> src/lib.rs:12:13
   |
12 |     optics!(x).view(s);
   |             ^ not found in `lens_rs::optics`

```

Versions used:

```
   Compiling lens-rs_derive v0.1.1 (https://github.com/TOETOE55/lens-rs.git#412ac405)
   Compiling lens-rs v0.1.21 (https://github.com/TOETOE55/lens-rs.git#412ac405)
```

**Comment by TOETOE55** [comment]
add
```toml
[package.metadata.inwelling]
lens-rs = true
```
in Cargo.toml?

I forgot to add it in README. sorry...

**Comment by maackle** [comment]
Great, that fixed my example! Now I can play with it :) Thank you

**Comment by TOETOE55** [comment]
enjoy it ;)
