### ISSUE TITLE
question: does somebody uses this project in production/release code? 

### ISSUE THREAD

**Issue by dzmitry-lahoda** [TOETOE55/lens-rs#15]
i searched oss projects too, but `lens` makes it hard to search

**Comment by TOETOE55** [comment]
thanks reporting~

I don't think anyone has used it yet, and it's not suitable for use in a production environment at the moment.

I am waiting for https://doc.rust-lang.org/beta/unstable-book/language-features/adt-const-params.html to be stabilized before I perform a refactoring, which will at least reduce the amount of code generated.

As for the issue of code search, I don't have any good ideas at the moment.

**Comment by dzmitry-lahoda** [comment]
@TOETOE55 thank you, so examples look very production oriented.

my current search is:

- https://crates.io/crates/lens-rs/reverse_dependencies
- https://github.com/search?q=lens_rs++language%3ARust&type=repositories&l=Rust

Interesting exploration could be how lens/prism can be combined with Clone on Write.
