### ISSUE TITLE
derive(Prism) fails if variant has same name as inner type

### ISSUE THREAD

**Issue by maackle** [TOETOE55/lens-rs#9]
The following fails because the variant `E1::A` collides with struct `A`

```rust
use lens_rs::*;

pub struct A {
    x: u32,
}

#[derive(Prism)]
pub enum E1 {
    #[optic]
    A(A),
}
```

Error:

```
3  | / pub struct A {
4  | |     x: u32,
5  | | }
   | |_- you might have meant to refer to this struct
...
10 |       A(A),
   |         ^ not a type
   |
help: consider importing one of these items instead
   |
1  | use crate::enums::A;
   |
1  | use crate::optics::A;
   |
1  | use lens_rs::optics::A;
   |
```

Note that it works if the variant is named differently from the type. This compiles:

```rust
pub struct B {
    x: u32,
}

#[derive(Prism)]
pub enum E2 {
    #[optic]
    A(B),
}
```

Is there a workaround for this? We have a large project that already has enums similar to `E1` and this problem is one of the things preventing me from using lens-rs. (Another is a problem with inwelling getting confused about our project structure but that's a different issue.)

**Comment by TOETOE55** [comment]
Thanks for the feedback! The problem has been located. Because of the asterisk wildcard syntax used when `Prims` is expanded, the name of the variant overrides the name of the type.

```rust
quote! {
        impl #params lens_rs::#optics_trait<lens_rs::optics::#var_name<#prism_param>, #image_param> for #ty
        where
            #constraints
        {
            #[inline] fn preview_ref(&self, optics: lens_rs::optics::#var_name<#prism_param>) -> Option<&#image_param> {
                use #ty_name::*; // **HERE**
                match self {
                    #var_name(x) => <#field_ty as lens_rs::#optics_trait<#prism_param, #image_param>>::preview_ref(x, optics.0),
                     _ => Option::None,
                }
            }
        }
    }
```

I will fix it when I am free.

workaround:
```
#[derive(Prism)]
pub enum E1 {
    #[optic]
    A(crate::A),
}
```

**Comment by maackle** [comment]
Without knowing what I'm doing, I created #10 which fixed the problem for me, I hope it can be of some help
